name: Generate Datas

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Debugging (optional)
      - name: Debug Info
        run: |
          echo "Checking GitHub Workspace..."
          ls -la
      
      # Generate Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: shivantika04
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
